server {
    # Wewnątrz Dockera używamy standardowego portu 80 (jest to bezpieczne)
    listen 80;

    # Przekierowanie do Django (zwróć uwagę na adres "http://backend:8000")
    location /api/ {
        proxy_pass http://backend:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Przekierowanie panelu admina
    location /admin/ {
        proxy_pass http://backend:8000/admin/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Przekierowanie do React/Vite (zwróć uwagę na adres "http://frontend:5173")
    location / {
        proxy_pass http://frontend:5173/;
        proxy_set_header Host $host;
        
        # Konfiguracja pod WebSockety (dla Vite HMR)
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
